export async function generateInterview(
    jobRole,
    jobDescription,
    yearsOfExperience
) {
    const apiKey = process.env.NEXT_PUBLIC_OPENAI_API?.trim();
    if (!apiKey) {
        throw new Error("NEXT_PUBLIC_OPENAI_API key is not configured.");
    }

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${apiKey}`,
            "HTTP-Referer": "http://localhost:3000",
            "X-Title": "AI Interview Mocker",
        },
        body: JSON.stringify({
            model: "openai/gpt-oss-120b:free",
            messages: [
                {
                    role: "user",
                    content: `
You are an expert technical interviewer.

Job Role: ${jobRole}

Tech Stack / Job Description:
${jobDescription}

Years of Experience:
${yearsOfExperience}

Generate exactly 2 interview questions with answers.

Return ONLY valid JSON array of objects. Do not include any markdown format or additional text.

[
    {
      "question": "question text",
      "answer": "answer text"
    }
]
`,
                },
            ],
        }),
    });

    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenRouter API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    let content = data.choices[0].message.content;

    // Clean up potential markdown code block wrappers if generated by the model
    content = content.replace(/^```json\s*/i, "").replace(/```\s*$/, "").trim();

    return JSON.parse(content);
}

export async function generateFeedback(question, userAnswer) {
    const apiKey = process.env.NEXT_PUBLIC_OPENAI_API?.trim();

    if (!apiKey) {
        throw new Error("NEXT_PUBLIC_OPENAI_API key is not configured.");
    }

    const feedbackPrompt = "Question:" + question +
        ", User Answer:" + userAnswer + ",Depends on question and user answer for given interview question" +
        "please give us rating for answer and feedback as area of improvement if any " +
        "in just 3 to 5 lines to improve it in JSON format with rating and feedback field";

    const response = await fetch(
        "https://openrouter.ai/api/v1/chat/completions",
        {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${apiKey}`,
                "HTTP-Referer": "http://localhost:3000",
                "X-Title": "AI Interview Mocker",
            },
            body: JSON.stringify({
                model: "openai/gpt-oss-120b:free",
                messages: [
                    {
                        role: "user",
                        content: feedbackPrompt,
                    },
                ],
            }),
        }
    );

    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(
            `OpenRouter API error: ${response.status} - ${errorText}`
        );
    }

    const data = await response.json();

    let content = data.choices[0].message.content;

    content = content
        .replace(/^```json\s*/i, "")
        .replace(/```\s*$/, "")
        .trim();

    return JSON.parse(content);
}